language: rust
sudo: false
rust:
  - stable

env:
  global:
    - EGLOT_TESTING=t # For kicks, so I don't forget this syntax
  matrix:
    - EMACS_VERSION=26-prerelease

install:
  - curl -LO https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  # Configure $PATH: Emacs installed to /tmp/emacs
  - export PATH=/tmp/emacs/bin:${PATH}
  - emacs --version
  # Install RLS
  - rustup update
  - rustup component add rls-preview rust-analysis rust-src
  # Install https://github.com/palantir/python-language-server
  - virtualenv .
  - . ./bin/activate
  - pip install 'python-language-server[all]'
    
script:
  - make check

